<?php
define('ROOT', $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR);
define('BASE', ROOT . 'libs' . DIRECTORY_SEPARATOR . 'base' . DIRECTORY_SEPARATOR);
define('CNF', BASE . 'cnfs' . DIRECTORY_SEPARATOR);